apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-ui
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: pokedex-ui
  template:
    metadata:
      labels:
        app: pokedex-ui
    spec:
      containers:
      - image: pokeapi:0.1
        name: pokedex-ui
        env:
        - name: POKEDEX_NAME
          valueFrom:
            configMapKeyRef:
              name: pokedex-cm
              key: NAME
        - name: POKEDEX_START_NUMBER
          valueFrom:
            configMapKeyRef:
              name: pokedex-cm
              key: START
        - name: POKEDEX_END_NUMBER
          valueFrom:
            configMapKeyRef:
              name: pokedex-cm
              key: STOP
        ports:
        - containerPort: 3000
